Add namespace to manifest selector
charmed-kubernetes/opa-gatekeeper-operators pull request #9
Opened 2022-08-29 13:23 UTC by nsklikas

Some of the excluded resources in the audit charm didn't match to the ones in the manifests which caused problems with the manager charm.

2022-08-29 13:35 UTC, stonepreston requested changes

2022-08-29 13:35 UTC, stonepreston commented on opa-audit-operator/src/manifests.py
>          apiVersion="policy/v1beta1",
btw v1beta1 PodDisruption budget is gone in 1.25 and needs to be changed to policy/v1. There isnt a new release containing this in the upstream repo, but the [master branch](https://github.com/open-policy-agent/gatekeeper/blob/7a5cc6fa11ba59dc1127716a7f1ab3850c30da14/deploy/gatekeeper.yaml#L2600) does fix this. We should probably update the manifests to use this master version in the meantime until they make a new release. Currently things would fail on a 1.25 cluster.

2022-08-29 15:46 UTC, nsklikas commented on opa-audit-operator/src/manifests.py
>          apiVersion="policy/v1beta1",
As we discussed I pushed the new manifests under the `3.10.0-beta` directory and switched the default version to that.

After the official `3.10.0` is released then we will drop both `3.9.0` and `3.10.0-beta` manifests

2022-08-30 15:19 UTC, stonepreston approved these changes

2022-08-30 15:19 UTC, merged